version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.21.1
    - 5.24.0
    - 5.24.2
    - 5.24.4
    - 5.26.0
    - 5.26.1
    - 5.26.3
    - 5.27.0
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.34.0
    - 5.35.0
    - 5.36.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.23
    - 14.14.24
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.32
    - 14.14.33
    - 15.0.0
  - dependency-name: postcss
    versions:
    - 8.2.11
    - 8.2.12
    - 8.2.7
  - dependency-name: tailwindcss
    versions:
    - 2.1.0
  - dependency-name: preact-render-to-string
    versions:
    - 5.1.13
    - 5.1.14
    - 5.1.15
    - 5.1.16
    - 5.1.19
  - dependency-name: next
    versions:
    - 10.1.0
    - 10.1.2
    - 10.1.3
  - dependency-name: next-plugin-preact
    versions:
    - 3.0.4
  - dependency-name: graphql-tag
    versions:
    - 2.12.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
